<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestLazy extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'TestLazy', 8, true, true, false, null, null),
				'city' => LightMetaProperty::fill(new LightMetaProperty(), 'city', 'city_id', 'integerIdentifier', 'TestCity', null, true, false, false, 1, 3),
				'cityOptional' => LightMetaProperty::fill(new LightMetaProperty(), 'cityOptional', 'city_optional_id', 'integerIdentifier', 'TestCity', null, false, false, false, 1, 3),
				'enum' => LightMetaProperty::fill(new LightMetaProperty(), 'enum', 'enum_id', 'enumeration', 'ImageType', null, false, false, false, 1, 3)
			);
		}
	}
?>