<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoCredentials extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'nickname' => LightMetaProperty::fill(new LightMetaProperty(), 'nickname', null, 'string', null, 255, true, true, false, null, null),
				'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 40, true, true, false, null, null)
			);
		}
	}
?>