<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestContactValueExtended extends ProtoTestContactValue
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'web' => LightMetaProperty::fill(new LightMetaProperty(), 'web', null, 'string', null, 255, true, true, false, null, null),
						'skype' => LightMetaProperty::fill(new LightMetaProperty(), 'skype', null, 'string', null, 255, true, true, false, null, null)
					)
				);
		}
	}
?>