<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestItem extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'TestItem', 8, true, true, false, null, null),
				'subItems' => LightMetaProperty::fill(new LightMetaProperty(), 'subItems', 'sub_items_id', 'identifierList', 'TestSubItem', null, false, false, false, 2, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 50, true, true, false, null, null)
			);
		}
	}
?>