<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestStringIdentifierRelated extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'TestStringIdentifierRelated', 8, true, true, false, null, null),
				'test' => LightMetaProperty::fill(new LightMetaProperty(), 'test', 'test_id', 'scalarIdentifier', 'TestStringIdentifier', null, false, false, false, 1, null)
			);
		}
	}
?>