<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestUser extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'TestUser', 8, true, true, false, null, null),
				'credentials' => InnerMetaProperty::fill(new InnerMetaProperty(), 'credentials', 'credentials_id', 'identifier', 'Credentials', null, true, false, true, 1, null),
				'lastLogin' => LightMetaProperty::fill(new LightMetaProperty(), 'lastLogin', 'very_custom_field_name', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'registered' => LightMetaProperty::fill(new LightMetaProperty(), 'registered', null, 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'strangeTime' => LightMetaProperty::fill(new LightMetaProperty(), 'strangeTime', 'strange_time', 'time', 'Time', null, false, true, false, null, null),
				'city' => LightMetaProperty::fill(new LightMetaProperty(), 'city', 'city_id', 'integerIdentifier', 'TestCity', null, true, false, false, 1, null),
				'firstOptional' => LightMetaProperty::fill(new LightMetaProperty(), 'firstOptional', 'first_optional_id', 'integerIdentifier', 'TestCity', null, false, false, false, 1, null),
				'secondOptional' => LightMetaProperty::fill(new LightMetaProperty(), 'secondOptional', 'second_optional_id', 'integerIdentifier', 'TestCity', null, false, false, false, 1, null),
				'parts' => LightMetaProperty::fill(new LightMetaProperty(), 'parts', 'parts_id', 'identifierList', 'TestPart', null, false, false, false, 2, null),
				'encapsulants' => LightMetaProperty::fill(new LightMetaProperty(), 'encapsulants', 'test_encapsulant_id', 'identifierList', 'TestEncapsulant', null, false, false, false, 3, null),
				'url' => LightMetaProperty::fill(new LightMetaProperty(), 'url', null, 'httpUrl', 'HttpUrl', 256, false, true, false, null, null),
				'properties' => LightMetaProperty::fill(new LightMetaProperty(), 'properties', null, 'hstore', 'Hstore', null, false, true, false, null, null),
				'ip' => LightMetaProperty::fill(new LightMetaProperty(), 'ip', null, 'inet', null, null, false, true, false, null, null)
			);
		}
	}
?>