<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestBinaryStuff extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'scalarIdentifier', 'TestBinaryStuff', 40, true, true, false, null, null),
				'data' => LightMetaProperty::fill(new LightMetaProperty(), 'data', null, 'binary', null, null, true, true, false, null, null)
			);
		}
	}
?>