<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2011-02-09 19:29:32                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestRange extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'start' => LightMetaProperty::fill(new LightMetaProperty(), 'start', null, 'date', 'Date', null, true, true, false, null, null),
				'end' => LightMetaProperty::fill(new LightMetaProperty(), 'end', null, 'date', 'Date', null, false, true, false, null, null),
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'TestRange', 8, true, true, false, null, null),
				'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, null, false, true, false, null, null)
			);
		}
	}
?>