<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestSubItem extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'TestSubItem', 8, true, true, false, null, null),
				'item' => LightMetaProperty::fill(new LightMetaProperty(), 'item', 'test_item_id', 'integerIdentifier', 'TestItem', null, true, false, false, 1, null),
				'encapsulant' => LightMetaProperty::fill(new LightMetaProperty(), 'encapsulant', 'encapsulant_id', 'integerIdentifier', 'TestEncapsulant', null, true, false, false, 1, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 50, true, true, false, null, null)
			);
		}
	}
?>