<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestPart extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'TestPart', 8, true, true, false, null, null),
				'testUser' => LightMetaProperty::fill(new LightMetaProperty(), 'testUser', 'test_user_id', 'integerIdentifier', 'TestUser', null, false, false, false, 1, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 50, true, true, false, null, null)
			);
		}
	}
?>