<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestParentObject extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'TestParentObject', 8, true, true, false, null, null),
				'root' => LightMetaProperty::fill(new LightMetaProperty(), 'root', 'root_id', 'integerIdentifier', 'TestChildObject', null, false, false, false, 1, 3)
			);
		}
	}
?>