<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoTestUserWithContactExtended extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'TestUserWithContactExtended', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 255, true, true, false, null, null),
				'surname' => LightMetaProperty::fill(new LightMetaProperty(), 'surname', null, 'string', null, 255, false, true, false, null, null),
				'contactExt' => InnerMetaProperty::fill(new InnerMetaProperty(), 'contactExt', 'contact_ext_id', 'identifier', 'TestContactValueExtended', null, true, false, true, 1, null)
			);
		}
	}
?>