<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestType extends IdentifiableObject
	{
		protected $objects = null;
		protected $name = null;
		
		public function __sleep()
		{
			return array('id', 'name');
		}
		
		/**
		 * @return TestTypeObjectsDAO
		**/
		public function getObjects($lazy = false)
		{
			if (!$this->objects || ($this->objects->isLazy() != $lazy)) {
				$this->objects = new TestTypeObjectsDAO($this, $lazy);
			}
			
			return $this->objects;
		}
		
		/**
		 * @return TestType
		**/
		public function fillObjects($collection, $lazy = false)
		{
			$this->objects = new TestTypeObjectsDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->objects->mergeList($collection);
			
			return $this;
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return TestType
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
	}
?>