<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2011-02-09 19:00:17                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCredentials
	{
		protected $nickname = null;
		protected $password = null;
		
		public function __sleep()
		{
			return array('nickname', 'password');
		}
		
		public function getNickname()
		{
			return $this->nickname;
		}
		
		/**
		 * @return Credentials
		**/
		public function setNickname($nickname)
		{
			$this->nickname = $nickname;
			
			return $this;
		}
		
		public function getPassword()
		{
			return $this->password;
		}
		
		/**
		 * @return Credentials
		**/
		public function setPassword($password)
		{
			$this->password = $password;
			
			return $this;
		}
	}
?>