<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2011-02-09 18:30:06                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestUserWithContact extends IdentifiableObject
	{
		protected $name = null;
		protected $surname = null;
		protected $contacts = null;
		
		public function __construct()
		{
			$this->contacts = new TestContactValue();
		}
		
		public function __sleep()
		{
			return array('id', 'name', 'surname', 'contacts');
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return TestUserWithContact
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getSurname()
		{
			return $this->surname;
		}
		
		/**
		 * @return TestUserWithContact
		**/
		public function setSurname($surname)
		{
			$this->surname = $surname;
			
			return $this;
		}
		
		/**
		 * @return TestContactValue
		**/
		public function getContacts()
		{
			return $this->contacts;
		}
		
		/**
		 * @return TestUserWithContact
		**/
		public function setContacts(TestContactValue $contacts)
		{
			$this->contacts = $contacts;
			
			return $this;
		}
		
		/**
		 * @return TestUserWithContact
		**/
		public function dropContacts()
		{
			$this->contacts = null;
			
			return $this;
		}
	}
?>