<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestItem extends NamedObject
	{
		protected $subItems = null;
		
		public function __sleep()
		{
			return array('id', 'name');
		}
		
		/**
		 * @return TestItemSubItemsDAO
		**/
		public function getSubItems($lazy = false)
		{
			if (!$this->subItems || ($this->subItems->isLazy() != $lazy)) {
				$this->subItems = new TestItemSubItemsDAO($this, $lazy);
			}
			
			return $this->subItems;
		}
		
		/**
		 * @return TestItem
		**/
		public function fillSubItems($collection, $lazy = false)
		{
			$this->subItems = new TestItemSubItemsDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->subItems->mergeList($collection);
			
			return $this;
		}
	}
?>