<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2011-02-09 18:30:06                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestUserWithContactExtended extends IdentifiableObject
	{
		protected $name = null;
		protected $surname = null;
		protected $contactExt = null;
		
		public function __construct()
		{
			$this->contactExt = new TestContactValueExtended();
		}
		
		public function __sleep()
		{
			return array('id', 'name', 'surname', 'contactExt');
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return TestUserWithContactExtended
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getSurname()
		{
			return $this->surname;
		}
		
		/**
		 * @return TestUserWithContactExtended
		**/
		public function setSurname($surname)
		{
			$this->surname = $surname;
			
			return $this;
		}
		
		/**
		 * @return TestContactValueExtended
		**/
		public function getContactExt()
		{
			return $this->contactExt;
		}
		
		/**
		 * @return TestUserWithContactExtended
		**/
		public function setContactExt(TestContactValueExtended $contactExt)
		{
			$this->contactExt = $contactExt;
			
			return $this;
		}
		
		/**
		 * @return TestUserWithContactExtended
		**/
		public function dropContactExt()
		{
			$this->contactExt = null;
			
			return $this;
		}
	}
?>