<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2011-02-09 19:33:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestRange extends DateRange
	{
		protected $id = null;
		protected $description = null;
		
		public function __sleep()
		{
			return array_merge(
				parent::__sleep(),
				array('id', 'start', 'description')
			);
		}
		
		public function getId()
		{
			return $this->id;
		}
		
		/**
		 * @return TestRange
		**/
		public function setId($id)
		{
			$this->id = $id;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return TestRange
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
	}
?>