<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestObject extends IdentifiableObject
	{
		protected $types = null;
		protected $name = null;
		
		public function __sleep()
		{
			return array('id', 'name');
		}
		
		/**
		 * @return TestObjectTypesDAO
		**/
		public function getTypes($lazy = false)
		{
			if (!$this->types || ($this->types->isLazy() != $lazy)) {
				$this->types = new TestObjectTypesDAO($this, $lazy);
			}
			
			return $this->types;
		}
		
		/**
		 * @return TestObject
		**/
		public function fillTypes($collection, $lazy = false)
		{
			$this->types = new TestObjectTypesDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->types->mergeList($collection);
			
			return $this;
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return TestObject
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
	}
?>