<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestEncapsulant extends NamedObject
	{
		protected $cities = null;
		
		public function __sleep()
		{
			return array('id', 'name');
		}
		
		/**
		 * @return TestEncapsulantCitiesDAO
		**/
		public function getCities($lazy = false)
		{
			if (!$this->cities || ($this->cities->isLazy() != $lazy)) {
				$this->cities = new TestEncapsulantCitiesDAO($this, $lazy);
			}
			
			return $this->cities;
		}
		
		/**
		 * @return TestEncapsulant
		**/
		public function fillCities($collection, $lazy = false)
		{
			$this->cities = new TestEncapsulantCitiesDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->cities->mergeList($collection);
			
			return $this;
		}
	}
?>