<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2011-02-09 18:30:05                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestBinaryStuff extends IdentifiableObject
	{
		protected $data = null;
		
		public function __sleep()
		{
			return array('id', 'data');
		}
		
		public function getData()
		{
			return $this->data;
		}
		
		/**
		 * @return TestBinaryStuff
		**/
		public function setData($data)
		{
			$this->data = $data;
			
			return $this;
		}
	}
?>