<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2011-02-09 18:30:06                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestContactValue
	{
		protected $email = null;
		protected $icq = null;
		protected $phone = null;
		protected $city = null;
		protected $cityId = null;
		
		public function __sleep()
		{
			return array('email', 'icq', 'phone', 'cityId');
		}
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return TestContactValue
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getIcq()
		{
			return $this->icq;
		}
		
		/**
		 * @return TestContactValue
		**/
		public function setIcq($icq)
		{
			$this->icq = $icq;
			
			return $this;
		}
		
		public function getPhone()
		{
			return $this->phone;
		}
		
		/**
		 * @return TestContactValue
		**/
		public function setPhone($phone)
		{
			$this->phone = $phone;
			
			return $this;
		}
		
		/**
		 * @return TestCity
		**/
		public function getCity()
		{
			if (!$this->city && $this->cityId) {
				$this->city = TestCity::dao()->getById($this->cityId);
			}
			
			return $this->city;
		}
		
		public function getCityId()
		{
			return $this->cityId;
		}
		
		/**
		 * @return TestContactValue
		**/
		public function setCity(TestCity $city)
		{
			$this->city = $city;
			$this->cityId = $city->getId();
			
			return $this;
		}
		
		/**
		 * @return TestContactValue
		**/
		public function setCityId($id)
		{
			$this->city = null;
			$this->cityId = $id;
			
			return $this;
		}
		
		/**
		 * @return TestContactValue
		**/
		public function dropCity()
		{
			$this->city = null;
			$this->cityId = null;
			
			return $this;
		}
	}
?>