<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2011-02-09 18:30:05                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestParentObject extends IdentifiableObject
	{
		protected $root = null;
		protected $rootId = null;
		
		public function __sleep()
		{
			return array('id', 'rootId');
		}
		
		/**
		 * @return TestChildObject
		**/
		public function getRoot()
		{
			if (!$this->root && $this->rootId) {
				$this->root = TestChildObject::dao()->getById($this->rootId);
			}
			
			return $this->root;
		}
		
		public function getRootId()
		{
			return $this->rootId;
		}
		
		/**
		 * @return TestParentObject
		**/
		public function setRoot(TestChildObject $root)
		{
			$this->root = $root;
			$this->rootId = $root->getId();
			
			return $this;
		}
		
		/**
		 * @return TestParentObject
		**/
		public function setRootId($id)
		{
			$this->root = null;
			$this->rootId = $id;
			
			return $this;
		}
		
		/**
		 * @return TestParentObject
		**/
		public function dropRoot()
		{
			$this->root = null;
			$this->rootId = null;
			
			return $this;
		}
	}
?>