<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2011-02-09 18:30:05                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestPart extends NamedObject
	{
		protected $testUser = null;
		
		public function __sleep()
		{
			return array('id', 'testUser', 'name');
		}
		
		/**
		 * @return TestUser
		**/
		public function getTestUser()
		{
			return $this->testUser;
		}
		
		/**
		 * @return TestPart
		**/
		public function setTestUser(TestUser $testUser)
		{
			$this->testUser = $testUser;
			
			return $this;
		}
		
		/**
		 * @return TestPart
		**/
		public function dropTestUser()
		{
			$this->testUser = null;
			
			return $this;
		}
	}
?>