<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestUserWithContactExtended extends AutoTestUserWithContactExtended implements Prototyped, DAOConnected
	{
		/**
		 * @return TestUserWithContactExtended
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return TestUserWithContactExtendedDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('TestUserWithContactExtendedDAO');
		}
		
		/**
		 * @return ProtoTestUserWithContactExtended
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoTestUserWithContactExtended');
		}
		
		// your brilliant stuff goes here
	}
?>