<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestType extends AutoTestType implements Prototyped, DAOConnected
	{
		/**
		 * @return TestType
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return TestTypeDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('TestTypeDAO');
		}
		
		/**
		 * @return ProtoTestType
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoTestType');
		}
		
		// your brilliant stuff goes here
	}
?>