<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestItem extends AutoTestItem implements Prototyped, DAOConnected
	{
		/**
		 * @return TestItem
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return TestItemDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('TestItemDAO');
		}
		
		/**
		 * @return ProtoTestItem
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoTestItem');
		}
		
		// your brilliant stuff goes here
	}
?>