<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class TestPart extends AutoTestPart implements Prototyped, DAOConnected
	{
		/**
		 * @return TestPart
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return TestPartDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('TestPartDAO');
		}
		
		/**
		 * @return ProtoTestPart
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoTestPart');
		}
		
		// your brilliant stuff goes here
	}
?>