<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestParentObject extends AutoTestParentObject implements Prototyped, DAOConnected
	{
		/**
		 * @return TestParentObject
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return TestParentObjectDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('TestParentObjectDAO');
		}
		
		/**
		 * @return ProtoTestParentObject
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoTestParentObject');
		}
		
		// your brilliant stuff goes here
	}
?>