<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestLazy extends AutoTestLazy implements Prototyped, DAOConnected
	{
		/**
		 * @return TestLazy
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return TestLazyDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('TestLazyDAO');
		}
		
		/**
		 * @return ProtoTestLazy
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoTestLazy');
		}
		
		// your brilliant stuff goes here
	}
?>