<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestChildObject extends AutoTestChildObject implements Prototyped, DAOConnected
	{
		/**
		 * @return TestChildObject
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return TestChildObjectDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('TestChildObjectDAO');
		}
		
		/**
		 * @return ProtoTestChildObject
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoTestChildObject');
		}
		
		// your brilliant stuff goes here
	}
?>