<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestUser extends AutoTestUser implements Prototyped, DAOConnected
	{
		/**
		 * @return TestUser
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return TestUserDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('TestUserDAO');
		}
		
		/**
		 * @return ProtoTestUser
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoTestUser');
		}
		
		// your brilliant stuff goes here
	}
?>