<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class TestContactValue extends AutoTestContactValue implements Prototyped
	{
		/**
		 * @return TestContactValue
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoTestContactValue
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoTestContactValue');
		}
		
		// your brilliant stuff goes here
	}
?>