<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestObject extends AutoTestObject implements Prototyped, DAOConnected
	{
		/**
		 * @return TestObject
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return TestObjectDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('TestObjectDAO');
		}
		
		/**
		 * @return ProtoTestObject
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoTestObject');
		}
		
		// your brilliant stuff goes here
	}
?>