<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestObjectDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'test_object';
		}
		
		public function getObjectName()
		{
			return 'TestObject';
		}
		
		public function getSequence()
		{
			return 'test_object_id';
		}
	}
?>