<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTestCityDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'custom_table';
		}
		
		public function getObjectName()
		{
			return 'TestCity';
		}
		
		public function getSequence()
		{
			return 'custom_table_id';
		}
		
		public function uncacheLists()
		{
			TestUser::dao()->uncacheLists();
			
			return parent::uncacheLists();
		}
	}
?>