<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestObjectTypesDAO extends ManyToManyLinked
	{
		public function __construct(TestObject $testObject, $lazy = false)
		{
			parent::__construct(
				$testObject,
				TestType::dao(),
				$lazy
			);
		}
		
		/**
		 * @return TestObjectTypesDAO
		**/
		public static function create(TestObject $testObject, $lazy = false)
		{
			return new self($testObject, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'test_object_test_type';
		}
		
		public function getChildIdField()
		{
			return 'test_type_id';
		}
		
		public function getParentIdField()
		{
			return 'test_object_id';
		}
	}
?>