<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestEncapsulantCitiesDAO extends ManyToManyLinked
	{
		public function __construct(TestEncapsulant $testEncapsulant, $lazy = false)
		{
			parent::__construct(
				$testEncapsulant,
				TestCity::dao(),
				$lazy
			);
		}
		
		/**
		 * @return TestEncapsulantCitiesDAO
		**/
		public static function create(TestEncapsulant $testEncapsulant, $lazy = false)
		{
			return new self($testEncapsulant, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'test_encapsulant_custom_table';
		}
		
		public function getChildIdField()
		{
			return 'custom_table_id';
		}
		
		public function getParentIdField()
		{
			return 'test_encapsulant_id';
		}
	}
?>