<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2010-03-24 21:11:41                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TestItemSubItemsDAO extends OneToManyLinked
	{
		public function __construct(TestItem $testItem, $lazy = false)
		{
			parent::__construct(
				$testItem,
				TestSubItem::dao(),
				$lazy
			);
		}
		
		/**
		 * @return TestItemSubItemsDAO
		**/
		public static function create(TestItem $testItem, $lazy = false)
		{
			return new self($testItem, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'test_item_id';
		}
	}
?>